version: '3.8'
services:
  server: 
    build: ./server
    container_name: server
    ports:
    - "3001:3001"
    environment: 
     - mongodb+srv://umavemula2005:WJFYDMeud2BfPtbW@cluster0.rlxavnw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0


  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
